SELECT 
    MEMBER_PROFILE.MEMBER_NAME,
    REST_REVIEW.REVIEW_TEXT,
    DATE_FORMAT(REST_REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE
INNER JOIN
    REST_REVIEW
ON
    MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
WHERE
    MEMBER_PROFILE.MEMBER_ID IN
    (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING count(member_id) = (SELECT COUNT(REVIEW_TEXT) AS 'NUM'
    	        FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY NUM DESC
                LIMIT 1))
ORDER BY 
    REST_REVIEW.REVIEW_DATE ASC;
    