SELECT A.APNT_NO,
       P.PT_NAME,
       A.PT_NO,
       A.MCDP_CD,
       D.DR_NAME,
       A.APNT_YMD
FROM APPOINTMENT A
    LEFT JOIN PATIENT P ON A.PT_NO = P.PT_NO
    LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = 'CS'
    AND A.APNT_CNCL_YN = 'N'
    AND LEFT(APNT_YMD, 10) = '2022-04-13'
ORDER BY
    A.APNT_YMD ASC